apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriharideployment
  labels:
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: sriultimateimage
        image: ultimate-cicd:56
        ports:
        - containerPort: 80

